import type { AchievementDefinition } from "../../types/game";

export const achievements: AchievementDefinition[] = [
  { id: "first-budget", title: "First Budget", description: "Created or adjusted a budget plan." },
  { id: "saved-100", title: "Saved Your First $100", description: "Built savings past $100." },
  { id: "emergency-started", title: "Emergency Fund Started", description: "Set aside money for surprises." },
  { id: "emergency-fund-started", title: "Emergency Fund Started", description: "Calculated and started a future emergency cushion." },
  { id: "scam-spotted", title: "Scam Spotted", description: "Avoided a suspicious message or offer." },
  { id: "paid-in-full", title: "Paid in Full", description: "Handled a credit balance responsibly." },
  { id: "credit-climber", title: "Credit Climber", description: "Improved your credit score." },
  { id: "diversified", title: "Diversified", description: "Used more than one kind of investment." },
  { id: "needs-before-wants", title: "Needs Before Wants", description: "Protected essentials before extras." },
  { id: "receipt-detective", title: "Receipt Detective", description: "Caught a price or receipt detail." },
  { id: "interview-ready", title: "Interview Ready", description: "Prepared for work or career opportunities." },
  { id: "future-planner", title: "Future Planner", description: "Compared post-high-school paths." },
  { id: "insurance-aware", title: "Insurance Aware", description: "Understood premiums, deductibles, or risk." },
  { id: "compound-growth", title: "Compound Growth", description: "Let saved or invested money grow over time." },
  { id: "debt-dodger", title: "Debt Dodger", description: "Avoided unnecessary high-interest debt." },
  { id: "reflection-ready", title: "Reflection Ready", description: "Reached the final reflection summary." },
  { id: "values-checkpoint", title: "Values Checkpoint", description: "Named a money tradeoff before choosing." },
  { id: "smart-shopper-guide", title: "Smart Shopper Guide", description: "Used a shopper checklist instead of impulse." },
  { id: "budget-rebuilder", title: "Budget Rebuilder", description: "Recovered after a budget surprise." },
  { id: "alert-setter", title: "Alert Setter", description: "Used account alerts or automatic saving." },
  { id: "emergency-500", title: "Emergency $500", description: "Built a stronger starter emergency fund." },
  { id: "apr-aware", title: "APR Aware", description: "Noticed how card interest can change the real cost." },
  { id: "bnpl-aware", title: "BNPL Aware", description: "Compared Buy Now Pay Later with other options." },
  { id: "long-game-investor", title: "Long-Game Investor", description: "Chose a patient investing habit." },
  { id: "security-shield", title: "Security Shield", description: "Used a security checklist to protect money." },
  { id: "risk-ready", title: "Risk Ready", description: "Compared risk, premium, and deductible." },
  { id: "career-explorer", title: "Career Explorer", description: "Researched career paths and training." },
  { id: "scholarship-seeker", title: "Scholarship Seeker", description: "Took action to reduce future education cost." },
  { id: "tax-translator", title: "Tax Translator", description: "Connected paychecks, taxes, and take-home pay." },
  { id: "refund-ready", title: "Refund Ready", description: "Made a thoughtful tax refund plan." },
  { id: "entrepreneurial-thinker", title: "Entrepreneurial Thinker", description: "Tested an earning idea with costs in mind." },
  { id: "balanced-planner", title: "Balanced Planner", description: "Protected wellbeing while improving money habits." },
  { id: "subscription-sleuth", title: "Subscription Sleuth", description: "Converted small recurring charges into a yearly cost." },
  { id: "pay-yourself-first", title: "Pay Yourself First", description: "Moved money into savings before spending extras." },
  { id: "young-entrepreneur", title: "Young Entrepreneur", description: "Checked revenue, expenses, and profit before launching an idea." },
  { id: "first-cushion", title: "First Cushion", description: "Saved the first small emergency buffer." },
  { id: "shock-absorber", title: "Shock Absorber", description: "Kept options open when a surprise cost appeared." },
  { id: "rebuilt-stronger", title: "Rebuilt Stronger", description: "Refilled savings after using a cushion." },
  { id: "per-unit-thinker", title: "Per-Unit Thinker", description: "Used unit-rate thinking to compare real value." },
  { id: "read-the-total", title: "Read-the-Total", description: "Included fees or hidden costs before deciding." },
  { id: "walked-away", title: "Walked Away", description: "Paused and declined a pressure-based money choice." },
  { id: "auto-pilot-saver", title: "Auto-Pilot Saver", description: "Used a routine or automatic move to save." },
  { id: "streak-of-three", title: "Streak of Three", description: "Built a repeated saving or planning habit." },
  { id: "flexible-planner", title: "Flexible Planner", description: "Adjusted a budget after new information." },
  { id: "under-thirty", title: "Under Thirty", description: "Kept credit use or debt pressure low." },
  { id: "on-time-streak", title: "On-Time Streak", description: "Showed a steady on-time payment habit." },
  { id: "report-detective", title: "Report Detective", description: "Checked a report, receipt, or record for mistakes." },
  { id: "total-cost-thinker", title: "Total-Cost Thinker", description: "Compared the whole cost instead of one payment." },
  { id: "smaller-and-smarter", title: "Smaller-and-Smarter", description: "Avoided borrowing more than the plan needed." },
  { id: "steady-hand", title: "Steady Hand", description: "Stayed patient when a money outcome felt bumpy." },
  { id: "fee-aware", title: "Fee-Aware", description: "Noticed that fees can change long-term results." },
  { id: "doubling-estimator", title: "Doubling Estimator", description: "Used growth or Rule of 72 thinking." },
  { id: "verified-first", title: "Verified First", description: "Checked a source or sender before acting." },
  { id: "hung-up-the-lure", title: "Hung Up the Lure", description: "Refused a too-good-to-be-true money request." },
  { id: "two-step-guardian", title: "Two-Step Guardian", description: "Protected an account with an extra safety step." },
  { id: "net-pay-realist", title: "Net-Pay Realist", description: "Used take-home pay instead of gross pay." },
  { id: "practiced-and-ready", title: "Practiced and Ready", description: "Prepared before a work, interview, or pathway opportunity." },
  { id: "reliable-reference", title: "Reliable Reference", description: "Built trust through steady follow-through." },
  { id: "aid-decoder", title: "Aid Decoder", description: "Separated aid that helps from money that must be repaid." },
  { id: "fair-comparer", title: "Fair Comparer", description: "Compared different future paths without assuming one right answer." },
  { id: "true-cost-driver", title: "True-Cost Driver", description: "Included transportation ownership or upkeep costs." },
  { id: "backup-ready", title: "Backup Ready", description: "Built a backup plan that protects opportunity." },
  { id: "upfront-ready", title: "Upfront-Ready", description: "Planned for deposits or up-front costs." },
  { id: "right-sized-deductible", title: "Right-Sized Deductible", description: "Matched coverage choices to savings." },
  { id: "calm-coverage", title: "Calm Coverage", description: "Understood that protection can matter even without a claim." },
  { id: "knows-the-profit", title: "Knows the Profit", description: "Calculated revenue minus costs." },
  { id: "record-keeper", title: "Record Keeper", description: "Kept a useful proof trail or simple ledger." },
  { id: "did-the-math", title: "Did the Math", description: "Used math to make a better money decision." },
  { id: "worth-not-self-worth", title: "Worth Does Not Equal Self-Worth", description: "Reflected on what net worth does and does not measure." },
  { id: "kind-boundary", title: "Kind Boundary", description: "Protected a money boundary respectfully." },
  { id: "first-repair-step", title: "First Repair Step", description: "Took action after a money setback." },
  { id: "no-repeat", title: "No Repeat", description: "Used a prevention habit after a past mistake." },
  { id: "five-correct", title: "Five Correct", description: "Showed strong real-life math habits." },
  { id: "asked-for-help", title: "Asked for Help", description: "Used trusted support before a big money move." },
  { id: "generous-within-plan", title: "Generous Within Plan", description: "Helped while still protecting the plan." },
  { id: "fair-splitter", title: "Fair Splitter", description: "Used a clear and fair shared-cost plan." },
  { id: "two-way-support", title: "Two-Way Support", description: "Built support that works in both directions." },
  { id: "tax-and-tip-pro", title: "Tax-and-Tip Pro", description: "Handled percent-based totals carefully." }
];

export function getAchievement(id: string): AchievementDefinition | undefined {
  return achievements.find((achievement) => achievement.id === id);
}
